apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 50051
      #nodePort: 32765