apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      #nodePort: 32765