apiVersion: apps/v1
kind: Deployment
metadata:
  name: receivetime
  labels:
    app: receivetime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receivetime
  template:
    metadata:
      labels:
        app: receivetime
    spec:
      containers:
        - name: receivetime
          image: receivetime:latest
          imagePullPolicy: IfNotPresent #minikube 使用本地镜像
          ports:
            - containerPort: 50051
              name: grpc
          volumeMounts:
            - mountPath: /data/log
              name: log
      volumes:
        - hostPath:
            path: /data/log
            type: ""
          name: log
