apiVersion: v1
kind: Service
metadata:
  name: receivetime
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: receivetime
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      name: grpc
