apiVersion: v1
kind: Service
metadata:
  name: receivetime-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: receivetime-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 50051
